import {
  Bookmark,
  BookmarkOutline,
  Home,
  HomeOutline,
  MessageCircle,
  MessageCircleOutline,
  Person,
  PersonOutline,
  PlusSquare,
  PlusSquareOutline,
  Search,
  SearchOutline,
  TrendingUp,
  TrendingUpOutline,
} from '@/assets/icons/components'

export const linksData = [
  {
    id: 1,
    title: 'Feed',
    path: '/',
    icon: <HomeOutline stroke={'currentColor'} />,
    iconActive: <Home stroke={'currentColor'} />,
  },
  {
    id: 2,
    title: 'Create',
    path: '/create',
    icon: <PlusSquareOutline stroke={'currentColor'} />,
    iconActive: <PlusSquare stroke={'currentColor'} />,
  },
  {
    id: 3,
    title: 'Profile',
    path: '/profile',
    icon: <PersonOutline stroke={'currentColor'} />,
    iconActive: <Person stroke={'currentColor'} />,
  },
  {
    id: 4,
    title: 'Messenger',
    path: '/messenger',
    icon: <MessageCircleOutline stroke={'currentColor'} />,
    iconActive: <MessageCircle stroke={'currentColor'} />,
  },
  {
    id: 5,
    title: 'Search',
    path: '/search',
    icon: <SearchOutline stroke={'currentColor'} />,
    iconActive: <Search stroke={'currentColor'} />,
  },
  {
    id: 6,
    title: 'Statistics',
    path: '/statistics',
    icon: <TrendingUpOutline stroke={'currentColor'} />,
    iconActive: <TrendingUp stroke={'currentColor'} />,
  },
  {
    id: 7,
    title: 'Favorites',
    path: '/favorites',
    icon: <BookmarkOutline stroke={'currentColor'} />,
    iconActive: <Bookmark stroke={'currentColor'} />,
  },
]
